### ISSUE TITLE
Where can I find the preprocessing file processXcalibrOutput.R ?

### ISSUE THREAD

**Issue by MohamedRefaat92** [NKI-GCF/xcalibr#1]

**Comment by MohamedRefaat92** [comment]
Hi developer,

I'm following an analysis tutorial using Xcalibr and it seems that I need a file called processXcalibrOutput.R for the preprocessing step. As far as I could see, the file is not available on this repo.

Is it possible to have access to it?

Best,
Mohamed

**Comment by veldsla** [comment]
That file name does not ring a bell. I assume it's created by the person that created the process you are trying to follow.

**Comment by MohamedRefaat92** [comment]
Hi,

Thanks for your prompt response. I'll refer back to the person who developed the workflow I'm following.

Best,
Mohamed
